name: Android CI

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest # Corrected indentation (2 spaces)
    env:                   # Corrected indentation (2 spaces)
      ANDROID_HOME: /usr/local/lib/android/sdk
      GRADLE_USER_HOME: ${{ github.workspace }}/.gradle

    steps:                 # Corrected indentation (2 spaces)
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Clean Gradle Caches
      # This command forcefully removes the local Gradle caches for the build.
      # It's a common fix for "Failed to create Jar file" errors.
      run: rm -rf ${{ github.workspace }}/.gradle/caches/ # Corrected indentation (6 spaces)

    - name: Clean Gradle Caches (Force Fresh Download)
      run: |
        echo "Attempting to remove ~/.gradle/caches/ for a clean slate..."
        rm -rf ~/.gradle/caches/ &&
            
      

    # Cache Gradle dependencies
   # - name: Cache Gradle
   #   uses: actions/cache@v4
   #   with:
   #     path: |
   #       ~/.gradle/caches
   #       ~/.gradle/wrapper
   #       ${{ github.workspace }}/.gradle
   #     key: ${{ runner.os }}-greadle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
   #     restore-keys: |
   #       ${{ runner.os }}-gradle-

    # Cache Android SDK - this is the key addition
   # - name: Cache Android SDK
   #   uses: actions/cache@v4
   #   with:
   #     path: |
   #       $ANDROID_HOME
   #       ~/.android/cache
   #     key: ${{ runner.os }}-android-sdk-${{ hashFiles('**/build.gradle*', '**/gradle.properties') }}
   #     restore-keys: |
   #       ${{ runner.os }}-android-sdk-

    # Setup Gradle with built-in caching
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3
      with:
        gradle-version: '8.2'
#        cache-read-only: false

    - name: Set up Android SDK
      uses: android-actions/setup-android@v3
      with:
        # Enable caching for build-tools, platforms, and ndk
        cache: true
        cmdline-tools-version: 'latest'
        build-tools-version: '34.0.0'
        platform-version: '34'
        ndk-version: '25.2.9519653'

    - name: Accept Android licenses
      run: | # Corrected indentation (6 spaces for 'run', then 8 for multiline content)
        mkdir -p ~/.android
        touch ~/.android/repositories.cfg
        yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses || true

    - name: Build APK with Gradle
      run: gradle assembleDebug --refresh-dependencies
        

    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: app-debug
        path: app/build/outputs/apk/debug/app-debug.apk
